# Generated by Django 5.2.4 on 2025-07-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_userotp_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
