# Generated by Django 5.2.4 on 2025-07-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_emailverification_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
